"""
Django settings for loonblog project.

Generated by 'django-admin startproject' using Django 1.11.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'dgiyz$(w0w1rm2e$j0_7v7axufn$b+0g*(q2apo^%2*35%nx5r'

# SECURITY WARNING: don't run with debug turned on in production!



# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.admin',
    'widget_tweaks',
    'apps.account',
    'apps.about',
    'apps.blog',
    'apps.comment',
    'raven.contrib.django.raven_compat',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'loonblog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'services.common.context_processors.now_env',
            ],
        },
    },
]

WSGI_APPLICATION = 'loonblog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

DATETIME_FORMAT = 'Y-m-d H:i:s'
TIME_FORMAT = 'H:i:s'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

LOGIN_URL = '/account/login/'

AUTH_USER_MODEL = 'account.MyUser'


STATICFILES_DIRS = (
    # Put strings here, like "/home/html/static" or "C:/www/django/static".
    # Always use forward slashes, even on Windows.
    # Don't forget to use absolute paths, not relative paths.

    #     ("css", os.path.join(STATIC_ROOT,'css')),
    ("js", os.path.join(STATIC_ROOT, 'js')),
    ("css", os.path.join(STATIC_ROOT, 'css')),
    ("fonts", os.path.join(STATIC_ROOT, 'fonts')),
    ("image", os.path.join(STATIC_ROOT, 'image')),
    ("images", os.path.join(STATIC_ROOT, 'images')),
    ("ueditor", os.path.join(STATIC_ROOT, 'ueditor')),
    ("syntaxhighlighter", os.path.join(STATIC_ROOT, 'syntaxhighlighter')),
)



CACHES = {
    'default': {
        'BACKEND': 'redis_cache.cache.RedisCache',
        'LOCATION': '127.0.0.1:6379',
        "OPTIONS": {
            "CLIENT_CLASS": "redis_cache.client.DefaultClient",
        },
    },
}


UEDITER_SETTING = {
    "fileMaxSize": 10240000,
    "scrawlPathFormat": "",
    "imageUrlPrefix": "",
    "catcherFieldName": "source",
    "snapscreenPathFormat": "",
    "imageFieldName": "upfile",
    "imagePathFormat": "",
    "filePathFormat": "",
    "scrawlMaxSize": 10485760,
    "catcherPathFormat": "",
    "scrawlUrlPrefix": "",
    "videoAllowFiles": [".flv", ".swf", ".mkv", ".avi", ".rm", ".rmvb", ".mpeg", ".mpg", ".ogg", ".ogv", ".mov", ".wmv",
                        ".mp4", ".webm", ".mp3", ".wav", ".mid"],
    "imageManagerAllowFiles": [".png", ".jpg", ".jpeg", ".gif", ".bmp"],
    "fileManagerListPath": "",
    "imageManagerUrlPrefix": "",
    "scrawlActionName": "uploadscrawl",
    "imageAllowFiles": [".png", ".jpg", ".jpeg", ".gif", ".bmp"],
    "imageManagerListSize": 30,
    "imageManagerActionName": "listimage",
    "videoUrlPrefix": "",
    "fileManagerActionName": "listfile",
    "fileManagerAllowFiles": [".sql", ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".tif", ".psd.flv", ".swf", ".mkv",
                              ".avi", ".rm", ".rmvb", ".mpeg", ".mpg", ".ogg", ".ogv", ".mov", ".wmv", ".mp4", ".webm",
                              ".mp3", ".wav", ".mid", ".rar", ".zip", ".tar", ".gz", ".7z", ".bz2", ".cab", ".iso",
                              ".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx", ".pdf", ".txt", ".md", ".xml", ".exe",
                              ".com", ".dll", ".msi"],
    "snapscreenUrlPrefix": "",
    "snapscreenActionName": "uploadimage",
    "catcherLocalDomain": ["127.0.0.1", "localhost", "img.baidu.com"],
    "imageActionName": "uploadimage",
    "fileUrlPrefix": "",
    "catcherActionName": "catchimage",
    "imageManagerListPath": "",
    "scrawlFieldName": "upfile",
    "fileManagerUrlPrefix": "",
    "videoActionName": "uploadvideo",
    "fileAllowFiles": [".sql", ".jpg", ".jpeg", ".bmp", ".gif", ".png", ".xls", ".xlsx", ".rar", ".doc", ".docx",
                       ".zip", ".pdf", ".txt", ".swf", ".wmv"],
    "videoPathFormat": "",
    "fileFieldName": "upfile",
    "catcherUrlPrefix": "",
    "catcherMaxSize": 1048576,
    "fileManagerListSize": 30,
    "catcherAllowFiles": [".png", ".jpg", ".jpeg", ".gif", ".bmp"],
    "imageMaxSize": 10485760,
    "videoMaxSize": 10240000,
    "fileActionName": "uploadfile",
    "videoFieldName": "upfile"
}


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.163.com'
EMAIL_HOST_USER = 'loonapp@163.com'
EMAIL_HOST_PASSWORD = 'aA451391452'
EMAIL_FROM = 'loonapp@163.com'
# EMAIL_PORT = 25
SECURITY_EMAIL_SENDER = 'loonapp@163.com'
# EMAIL_USE_TLS = True
EMAIL_SUBJECT_PREFIX = '[LOONAPP]'

ADMIN_EMAIL = 'blackholll@163.com'

